spring:
  datasource:
    username: plateer
    password: 1234
    data-username: plateer
    data-password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/storyclub